mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_PASSWORD=docker
    - MYSQL_USER=docker
    - MYSQL_DATABASE=kakei_log_development
  build: ./container/mysql
  ports:
    - "3306:3306"
